CREATE TABLE ACADEMIC_STREAMS(
    ID NUMBER PRIMARY KEY,
    STREAM_NAME VARCHAR2(100),
    HEAD_STUDENT_ID NUMBER);
   -- FOREIGN KEY(HEAD_STUDENT_ID) REFERENCES STUDENTS(ID)

CREATE TABLE STUDENT_GROUPS(
    ID NUMBER PRIMARY KEY,
    GROUP_NAME VARCHAR2(100),
    ACADEMIC_STREAM_ID NUMBER,
    FOREIGN KEY (ACADEMIC_STREAM_ID) REFERENCES ACADEMIC_STREAMS(ID)
    );

CREATE TABLE STUDENTS(
    ID NUMBER PRIMARY KEY,
    STUDENT_NAME VARCHAR2(100),
    GROUP_ID NUMBER,
    FOREIGN KEY (GROUP_ID) REFERENCES STUDENT_GROUPS(ID)
    );
    
CREATE TABLE SERVER(
    ID NUMBER PRIMARY KEY,
    SERVER_NAME VARCHAR2(100)
    );
CREATE TABLE CLIENT(
    ID NUMBER PRIMARY KEY,
    CLIENT_NAME VARCHAR2(100),
    SERVER_ID NUMBER,
    FOREIGN KEY (SERVER_ID) REFERENCES SERVER(ID)
    );


ALTER TABLE ACADEMIC_STREAMS
ADD CONSTRAINT fk_head_student
FOREIGN KEY (HEAD_STUDENT_ID) REFERENCES STUDENTS(ID);