INSERT INTO STUDENT_GROUPS(ID, GROUP_NAME) VALUES(1, '153501');
INSERT INTO STUDENT_GROUPS(ID, GROUP_NAME) VALUES(2, '153502');
INSERT INTO STUDENT_GROUPS(ID, GROUP_NAME) VALUES(3, '153503');
INSERT INTO STUDENT_GROUPS(ID, GROUP_NAME) VALUES(4, '153504');

INSERT INTO STUDENTS(ID,STUDENT_NAME,GROUP_ID) VALUES (1,'Abramovich Pavel Nikolaevich', 1);
INSERT INTO STUDENTS(ID,STUDENT_NAME,GROUP_ID) VALUES (2, 'Bybko Alina Andreevna', 1);
INSERT INTO STUDENTS(ID,STUDENT_NAME,GROUP_ID) VALUES (3, 'Bychko Vasily Pavlovich', 2);
INSERT INTO STUDENTS(ID,STUDENT_NAME,GROUP_ID) VALUES (4, 'Glebtsova Elizaveta Nikolaevna', 2);
INSERT INTO STUDENTS(ID,STUDENT_NAME,GROUP_ID) VALUES (5, 'Grischuk Alexander Olegovich', 3);
INSERT INTO STUDENTS(ID,STUDENT_NAME,GROUP_ID) VALUES (6, 'Talay Artem Alexandrovich', 3);
INSERT INTO STUDENTS(ID,STUDENT_NAME,GROUP_ID) VALUES (7, 'Kosach Dmitry Anatolyevich', 4);
INSERT INTO STUDENTS(ID,STUDENT_NAME,GROUP_ID) VALUES (8, 'Kudlasevich Artur Ivanovich', 4);

