CREATE TABLE STUDENT_GROUPS(
    ID NUMBER PRIMARY KEY,
    GROUP_NAME VARCHAR2(100)
    );

CREATE TABLE STUDENTS(
    ID NUMBER PRIMARY KEY,
    STUDENT_NAME VARCHAR2(100),
    GROUP_ID NUMBER,
    FOREIGN KEY (GROUP_ID) REFERENCES STUDENT_GROUPS(ID)
    );
    
CREATE TABLE SERVER(
    ID NUMBER PRIMARY KEY,
    SERVER_NAME VARCHAR2(100)
    );
CREATE TABLE CLIENT(
    ID NUMBER PRIMARY KEY,
    CLIENT_NAME VARCHAR2(100)
    );
