CREATE TABLE STUDENTS(id NUMBER, name VARCHAR2(100), group_id NUMBER);
CREATE TABLE GROUPS(id NUMBER, name VARCHAR2(100), c_val NUMBER);
CREATE TABLE GROUPS (
    ID NUMBER,
    NAME VARCHAR2(100),
    C_VAL NUMBER DEFAULT 0
);