CREATE OR REPLACE TRIGGER UPDATE_C_VAL_IN_GROUP_TRIGGER
AFTER INSERT OR UPDATE OR DELETE ON STUDENTS
FOR EACH ROW
DECLARE
    NEW_GROUP_ID NUMBER;
    OLD_GROUP_ID NUMBER;
    
BEGIN
    IF INSERTING THEN
        NEW_GROUP_ID := :NEW.GROUP_ID;
        IF NEW_GROUP_ID IS NOT NULL THEN
            UPDATE GROUPS
            SET C_VAL = C_VAL + 1
            WHERE ID = NEW_GROUP_ID;
        END IF;
        
    ELSIF UPDATING THEN
        NEW_GROUP_ID := :NEW.GROUP_ID;
        OLD_GROUP_ID := :OLD.GROUP_ID;
        
        IF (NEW_GROUP_ID IS NOT NULL AND OLD_GROUP_ID <> NEW_GROUP_ID) THEN
            UPDATE GROUPS
            SET C_VAL = C_VAL + 1
            WHERE ID = NEW_GROUP_ID;
            
            UPDATE GROUPS
            SET C_VAL = C_VAL - 1
            WHERE ID = OLD_GROUP_ID;
        END IF;
        
    ELSIF DELETING THEN
        OLD_GROUP_ID := :OLD.GROUP_ID;
        
        IF OLD_GROUP_ID IS NOT NULL THEN
            UPDATE GROUPS
            SET C_VAL = C_VAL - 1
            WHERE ID = OLD_GROUP_ID;
        END IF;
        
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'UPDATE_C_VAL_IN_GROUP_TRIGGER!: ' || SQLERRM);
END;

------------------------------------------------
CREATE OR REPLACE TRIGGER UPDATE_GROUP_C_VAL
AFTER INSERT OR DELETE OR UPDATE OF GROUP_ID ON STUDENTS
FOR EACH ROW
DECLARE
    v_student_count NUMBER;
BEGIN
    IF INSERTING OR UPDATING THEN
        IF :NEW.GROUP_ID != :OLD.GROUP_ID THEN
            SELECT COUNT(*) INTO v_student_count FROM STUDENTS WHERE GROUP_ID = :NEW.GROUP_ID;
            UPDATE GROUPS SET C_VAL = v_student_count WHERE ID = :NEW.GROUP_ID;
        END IF;
        IF :OLD.GROUP_ID IS NOT NULL THEN
            SELECT COUNT(*) INTO v_student_count FROM STUDENTS WHERE GROUP_ID = :OLD.GROUP_ID;
            UPDATE GROUPS SET C_VAL = v_student_count WHERE ID = :OLD.GROUP_ID;
        END IF;
    ELSIF DELETING THEN
        SELECT COUNT(*) INTO v_student_count FROM STUDENTS WHERE GROUP_ID = :OLD.GROUP_ID;
        UPDATE GROUPS SET C_VAL = v_student_count WHERE ID = :OLD.GROUP_ID;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ошибка при обновлении C_VAL: ' || SQLERRM);
END;

DROP TRIGGER UPDATE_C_VAL_IN_GROUP_TRIGGER;