CREATE OR REPLACE TRIGGER DELETE_STUDENTS_AFTER_GROUP_DELETE
AFTER DELETE ON GROUPS
FOR EACH ROW
BEGIN
  DELETE FROM STUDENTS WHERE STUDENTS.GROUP_ID = :OLD.ID;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('MY ERROR WHILE DELETING: ' || SQLERRM);
END;

------

ALTER TABLE STUDENTS
DROP CONSTRAINT fk_students_groups;

DROP TRIGGER DELETE_STUDENTS_AFTER_GROUP_DELETE;

ALTER TABLE STUDENTS
ADD CONSTRAINT fk_students_groups
FOREIGN KEY (group_id)
REFERENCES GROUPS(id)
ON DELETE CASCADE;

 