CREATE OR REPLACE TRIGGER DELETE_STUDENTS_AFTER_GROUP_DELETE
AFTER DELETE ON GROUPS
FOR EACH ROW
BEGIN
  DELETE FROM STUDENTS WHERE group_id = :OLD.ID;
END;


ALTER TABLE STUDENTS
DROP CONSTRAINT fk_students_groups;

ALTER TABLE STUDENTS
ADD CONSTRAINT fk_students_groups
FOREIGN KEY (group_id)
REFERENCES GROUPS(id)
ON DELETE CASCADE;