CREATE OR REPLACE TRIGGER UPDATE_C_VAL_IN_GROUP_TRIGGER
AFTER INSERT OR UPDATE OR DELETE ON STUDENTS
FOR EACH ROW
DECLARE
    NEW_GROUP_ID STUDENTS.GROUP_ID%TYPE;
    OLD_GROUP_ID STUDENTS.GROUP_ID%TYPE;
    
BEGIN
    IF INSERTING THEN
        NEW_GROUP_ID := :NEW.GROUP_ID;
        IF NEW_GROUP_ID IS NOT NULL THEN
            UPDATE GROUPS
            SET C_VAL = C_VAL + 1
            WHERE ID = NEW_GROUP_ID;
        END IF;
        
    ELSIF UPDATING THEN
        NEW_GROUP_ID := :NEW.GROUP_ID;
        OLD_GROUP_ID := :OLD.GROUP_ID;
        
        IF (NEW_GROUP_ID IS NOT NULL AND OLD_GROUP_ID <> NEW_GROUP_ID) THEN
            UPDATE GROUPS
            SET C_VAL = C_VAL + 1
            WHERE ID = NEW_GROUP_ID;
            
            UPDATE GROUPS
            SET C_VAL = C_VAL - 1
            WHERE ID = OLD_GROUP_ID;
        END IF;
        
    ELSIF DELETING THEN
        OLD_GROUP_ID := :OLD.GROUP_ID;
        
        IF OLD_GROUP_ID IS NOT NULL THEN
            UPDATE GROUPS
            SET C_VAL = C_VAL - 1
            WHERE ID = OLD_GROUP_ID;
        END IF;
        
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'UPDATE_C_VAL_IN_GROUP_TRIGGER!: ' || SQLERRM);
END;