CREATE OR REPLACE TRIGGER DELETE_STUDENTS_AFTER_GROUP_DELETE
AFTER DELETE ON GROUPS
FOR EACH ROW
BEGIN
  DELETE FROM STUDENTS WHERE GROUP_ID = :OLD.ID;
  EXCEPTION
WHEN OTHERS THEN
    -- Вывод сообщения об ошибке и откат транзакции
    DBMS_OUTPUT.PUT_LINE('MY ERROR WHILE DELETING: ' || SQLERRM);
END;


ALTER TABLE STUDENTS
DROP CONSTRAINT fk_students_groups;

ALTER TABLE STUDENTS
ADD CONSTRAINT fk_students_groups
FOREIGN KEY (group_id)
REFERENCES GROUPS(id)
ON DELETE CASCADE;

DROP TRIGGER DELETE_STUDENTS_BEFORE_GROUP_DELETE;