GRANT CREATE TRIGGER TO SYS;
GRANT CREATE ANY TRIGGER TO SYS;
CREATE OR REPLACE TRIGGER VERIFY_STUDENTS_UNIQUE_ID
BEFORE INSERT OR UPDATE ON STUDENTS
FOR EACH ROW
DECLARE
    id_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO id_count FROM STUDENTS WHERE ID = :NEW.ID;
    IF id_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'ID MUST BE UNIQUE!');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20002, 'VERIFY_UNIQUE_ID ERROR!: ' || SQLERRM);
END;

Delete from students_audit;