DECLARE
    S_TIMESTAMP TIMESTAMP := TO_TIMESTAMP('2024-02-21 14:32:08', 'YYYY-MM-DD HH24:MI:SS');
BEGIN
    RESTORE_STUDENTS_BY_TIMESTAMP(S_TIMESTAMP);
END;

BEGIN
    ROLLBACK_STUDENTS_BY_SECONDS(50);
END;