INSERT INTO STUDENTS(NAME, AGE) VALUES ('Abramovich Pavel Nikolaevich', 20);
INSERT INTO STUDENTS(NAME, AGE) VALUES ('Abramovich Pavel Nikolaevich', 20);
INSERT INTO STUDENTS(NAME, AGE) VALUES ('Bybko Alina Andreevna', 21);
INSERT INTO STUDENTS(NAME, AGE) VALUES ('Bychko Vasily Pavlovich', 19);
INSERT INTO STUDENTS(NAME, AGE) VALUES ('Glebtsova Elizaveta Nikolaevna', 22);
INSERT INTO STUDENTS(NAME, AGE) VALUES ('Grischuk Alexander Olegovich', 18);
INSERT INTO STUDENTS(NAME, AGE) VALUES ('Korotkiy Pavel Igorevich', 23);
INSERT INTO STUDENTS(NAME, AGE) VALUES ('Kosach Dmitry Anatolyevich', 30);
INSERT INTO STUDENTS(NAME, AGE) VALUES ('Kudlasevich Artur Ivanovich', 25);
INSERT INTO STUDENTS(NAME, AGE) VALUES ('Pihtovnikova Maria Timurovna', 17);
INSERT INTO STUDENTS(NAME, AGE) VALUES ('Stovba Vladislav Alexandrovich', 29);

INSERT INTO STUDENTS(ID, NAME, AGE) VALUES (1, 'Abramovich Pavel Nikolaevich', 20);
INSERT INTO STUDENTS(ID, NAME, AGE) VALUES (2,'Bybko Alina Andreevna', 21);
INSERT INTO STUDENTS(ID, NAME, AGE) VALUES (3,'Bychko Vasily Pavlovich', 19);
INSERT INTO STUDENTS(ID, NAME, AGE) VALUES (4,'Glebtsova Elizaveta Nikolaevna', 22);
INSERT INTO STUDENTS(ID, NAME, AGE) VALUES (5,'Grischuk Alexander Olegovich', 18);
INSERT INTO STUDENTS(ID, NAME, AGE) VALUES (6,'Korotkiy Pavel Igorevich', 23);
INSERT INTO STUDENTS(ID, NAME, AGE) VALUES (7,'Kosach Dmitry Anatolyevich', 30);
INSERT INTO STUDENTS(ID, NAME, AGE) VALUES (8,'Kudlasevich Artur Ivanovich', 25);
INSERT INTO STUDENTS(ID, NAME, AGE) VALUES (9,'Pihtovnikova Maria Timurovna', 17);
INSERT INTO STUDENTS(ID, NAME, AGE) VALUES (10,'Stovba Vladislav Alexandrovich', 29);

INSERT INTO LESSONS(ID, TEACHER, NAME) VALUES (1,'Sirotko Sergei Ivanovich', 'OSISP');
INSERT INTO LESSONS(ID,TEACHER, NAME) VALUES (2, 'Davidchik Anton Vitalievich', 'Database');
INSERT INTO LESSONS(ID,TEACHER, NAME) VALUES (3, 'Kalugina Marina Alekseevna', 'Math');
INSERT INTO LESSONS(ID,TEACHER, NAME) VALUES (4, 'Roghov Maxim Gennadievich', 'OOP');
INSERT INTO LESSONS(ID,TEACHER, NAME) VALUES (5, 'Gritsenko Nikita Yurievich', 'MTRAN');
INSERT INTO LESSONS(ID,TEACHER, NAME) VALUES (6, 'Vladymtsev Vadim Denisovich', 'OAIP');

INSERT INTO EXAMS(ID, EXAM_DATE, LESSON_ID) VALUES(1, TO_DATE('2024/06/20','YYYY/MM/DD') ,1);
INSERT INTO EXAMS(ID, EXAM_DATE, LESSON_ID) VALUES(2, TO_DATE('2024/06/24','YYYY/MM/DD') ,2);
INSERT INTO EXAMS(ID, EXAM_DATE, LESSON_ID) VALUES(3, TO_DATE('2024/06/28','YYYY/MM/DD') ,3);
INSERT INTO EXAMS(ID, EXAM_DATE, LESSON_ID) VALUES(4, TO_DATE('2024/07/01','YYYY/MM/DD') ,4);
INSERT INTO EXAMS(ID, EXAM_DATE, LESSON_ID) VALUES(5, TO_DATE('2024/07/05','YYYY/MM/DD') ,5);
INSERT INTO EXAMS(ID, EXAM_DATE, LESSON_ID) VALUES(6, TO_DATE('2024/07/08','YYYY/MM/DD') ,6);

DELETE FROM STUDENTS;

DELETE FROM LESSONS;

DELETE FROM EXAMS;