
DROP TABLE LAB4.exams;
DROP TABLE LAB4.lessons;

CREATE TABLE LAB4.lessons (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    difficulty VARCHAR2(50)
)
/

CREATE TABLE LAB4.exams(
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    lesson_id NUMBER,
    exam_date DATE,
    CONSTRAINT FK_LESSONS FOREIGN KEY (lesson_id) REFERENCES LAB4.lessons(id)
)
/

-- Заполнение таблицы lessons
INSERT INTO LAB4.lessons (name, difficulty) VALUES ('math', 'hard');
INSERT INTO LAB4.lessons (name, difficulty) VALUES ('history', 'medium');
INSERT INTO LAB4.lessons (name, difficulty) VALUES ('PE', 'simple');

-- Заполнение таблицы exams
INSERT INTO LAB4.exams (exam_date, lesson_id) VALUES (TO_DATE('2024/06/20', 'YYYY/MM/DD'), 1);
INSERT INTO LAB4.exams (exam_date, lesson_id) VALUES (TO_DATE('2024/06/28', 'YYYY/MM/DD'), 2);
INSERT INTO LAB4.exams (exam_date, lesson_id) VALUES (TO_DATE('2024/06/01', 'YYYY/MM/DD'), 3);